### ISSUE TITLE
Cant see data for evaluation.py

### ISSUE THREAD

**Issue by gowriaddepalli** [clovaai/wsolevaluation#31]
I cant find this folder **train_log/scoremaps/** for CUB dataset. I am trying to use your evaluation only script. Could you please tell me the procedure to run this code on heatmaps. How do we generate or run your evaluation.py on custom object detection datasets?

**Comment by coallaoh** [comment]
Thank you for your interest in our work 👍 

> Could you please tell me the procedure to run this code on heatmaps.

About the evaluation-only script and preparing the folder structure, did you take a look at our documentation? https://github.com/clovaai/wsolevaluation#4-wsol-evaluation

> How do we generate or run your evaluation.py on custom object detection datasets?

Our evaluation is designed for object localization (prediction: heatmap, GT: boxes or pixel-wise label map), rather than object detection (prediction: boxes with confidence scores, GT: boxes). The code is not going to work for the detection task. Can you confirm if your dataset is based on object detection or localization?

**Comment by gowriaddepalli** [comment]
I am running this task for localization, i have a custom dataset with images, its masks and cam images. could you please detail me on how to run the evaluation.py code.

**Comment by junsukchoe** [comment]
Hello,

The score maps are automatically saved at the end of training.
Then, run this:

```
python evaluation.py --scoremap_root=train_log/{output_dir_name}/scoremaps/ \
                     --metadata_root=metadata/ \
                     --mask_root=dataset/ \
                     --dataset_name=CUB \
                     --split=test \
                     --cam_curve_interval=0.001
```

**Comment by coallaoh** [comment]
Okay, thanks for the clarification 👍 

But still, if you ask for more details on the procedure already described in our documentation, I can only re-iterate what's written in our documentation (https://github.com/clovaai/wsolevaluation#4-wsol-evaluation). Can you provide more inputs for us to help you better? I.e., which part of the documentation was not clear for you?

**Comment by coallaoh** [comment]
Closing the issue, assuming the question was answered :)
Please re-open the issue as necessary.
