### ISSUE TITLE
openimages pxap perf changed between maxboxacc and maxboxaccv2. why?

### ISSUE THREAD

**Issue by sbelharbi** [clovaai/wsolevaluation#49]
hi,
in https://arxiv.org/pdf/2001.07437.pdf , the pxap performance changed between using maxboxacc (tab.2) and using maxboxaccv2 (tab.8) over openimages. i didnt expect that.
why is that?
because the validation (for model selection) on openimages is done using pxap (as for test as well), using maxboxacc or maxboxaccv2 in the code configuration should not impact the results on pxap, right?

or did you run a new 30 random trials for hyper-parameters search that led to different best hyper-parameters for pxap tab.8? or simply due to randomness if the code is not reproducible (running the same experiment twice  with the same settings does not lead to the exact same results...)?

![tab 2](https://user-images.githubusercontent.com/23446793/124291055-26b99680-db22-11eb-9724-2e99c078b4db.png)

![tab 8](https://user-images.githubusercontent.com/23446793/124291053-26b99680-db22-11eb-9495-ee63027c52ea.png)

thanks

**Comment by junsukchoe** [comment]
Thanks for your interest in our work :)

Yes, the performances on OpenImages dataset have been changed. This is because we ran new 30 trials for OpenImages. Due to the randomness, the new results are not the same as the initial experiments. But we would like to note that our main conclusion does not change: WSOL methods after CAM have not improved significantly.

**Comment by sbelharbi** [comment]
ok, thanks for the clarification.
