### ISSUE TITLE
Optimal threshold for test set

### ISSUE THREAD

**Issue by won-bae** [clovaai/wsolevaluation#5]
Hi,

I have a question about the evaluation. I've tried to understand how the optimal threshold is used in the test time. It seems you are searching the optimal threshold for test set again instead of using the optimal threshold that is found using validation set. Or am I missing something? Please correct me if I am wrong. I cannot really find the line of code where the optimal threshold is stored for test set. Thank you.

**Comment by coallaoh** [comment]
Thanks for your continued interest :)

We use the oracle score map threshold in the corresponding evaluation set.
If it is the validation set, we use the validation-optimal threshold; if it is the test set, we use the test-optimal threshold. The threshold is not transferred across the val and test. We do this in order to eliminate the dependence of performance on the choice of threshold; in other words, we treat the choice of threshold as part of the evaluation, instead of as part of the method as done in many prior WSOL works. There have been certain cases where mere the major improvements in localisation are led by better choices of score map thresholds while the paper attributes the improvements to other design choices (e.g. feature erasing thresholds). Our performance metric is measuring the _upper bound_ of the box-based localisation accuracy of the given score maps.

Hope it clarifies your question.

**Comment by won-bae** [comment]
Thanks for the clarification. Now I got it!
